services:
  servicebus-emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    ports:
      - "5672:5672" # AMQP
      - "5300:5300" # Management
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
      SQL_SERVER: "sqledge"
    volumes:
      - "./servicebus-emulator/Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    depends_on:
      sqledge:
        condition: service_healthy
    networks:
      sb-network:
        aliases:
          - sbemulatorns
      spd-local-network:
        aliases:
          - sbemulatorns

  sqledge:
    container_name: "sqledge"
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "1433:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - sb-network

networks:
  sb-network:
    driver: bridge
  spd-local-network:
    external: true
